---
- name: Créer dossier de config
  file:
    path: /etc/rancher/rke2
    state: directory

- name: Générer le fichier config
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: Installer RKE2 agent
  shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=agent sh -

- name: Démarrer le service RKE2 agent
  systemd:
    name: rke2-agent
    state: started
    enabled: true
