---
- name: Installer Helm
  shell: curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

- name: Ajouter dépôts Helm
  shell: |
    helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
    helm repo add jetstack https://charts.jetstack.io
    helm repo update

# === Attendre que le contrôleur NGINX soit prêt ===
- name: Attendre que le contrôleur NGINX soit prêt
  shell: kubectl get pods -n kube-system | grep "rke2-ingress-nginx-controller" | grep "1/1"
  register: nginx_status
  retries: 30
  delay: 10
  until: nginx_status.rc == 0

- name: Installer cert-manager
  shell: |
    kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.crds.yaml
    helm upgrade -i cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace

# === Attendre que cert-manager soit prêt ===
- name: Attendre que cert-manager soit prêt
  shell: kubectl get pods -n cert-manager | grep "Running"
  register: cert_status
  retries: 30
  delay: 10
  until: cert_status.rc == 0

- name: Installer Rancher
  shell: |
    helm upgrade -i rancher rancher-latest/rancher \
      --create-namespace \
      --namespace cattle-system \
      --set hostname={{ rancher_hostname }} \
      --set bootstrapPassword={{ rancher_password }} \
      --set replicas=1
